version: "3.9"

networks:
  int_network:

services:
  controlsvc:
    image: majumi/clientappservice:appservice
    ports:
      - published: 5010
        target: 5010
    networks:
      - int_network
    deploy:
      replicas: 1
